#! /bin/sh

sxhkd &
compton &
dunst &
xscreensaver &
polybar example &
redshift -P -O 3500 &

bspc config border_width         6
bspc config focused_border_color "#a2a2a2"
bspc config window_gap           0
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

bash $HOME/.scripts/bspwmstartup
(ps x | grep bspswallow | grep -v grep) || bspswallow &
