#!/usr/bin/env bash
ls /tmp/wall.png && rm /tmp/wall.png
scrot /tmp/wall.png
file="/tmp/wall.png"
convert -spread 12% $file $file
i3lock -i $file "--insidecolor=0000001c" "--ringcolor=0000003e" \
        "--linecolor=00000000" "--keyhlcolor=ffffff80" "--ringvercolor=ffffff00" \
        "--separatorcolor=22222260" "--insidevercolor=ffffff1c" \
        "--ringwrongcolor=ffffff55" "--insidewrongcolor=ffffff1c" \
        "--verifcolor=ffffff00" "--wrongcolor=ff000000" "--timecolor=ffffff00" \
        "--datecolor=ffffff00" "--layoutcolor=ffffff00"
