#!/usr/bin/env bash
# dwm Startup script

sxhkd &
compton &

#set wallpaper
bash $HOME/.scripts/wallpaperinit

#set caps to esc
bash $HOME/.scripts/capstoesc

#welcome message and battery level
bash $HOME/.scripts/batterychecker &

